version: "3.8"

networks:
  oni:
    name: oni
    driver: bridge

volumes:
  postgres_data:
  opensearch_data:

services:
  db:
    restart: always
    image: postgres:13-alpine
    hostname: db
    tty: true
    environment:
      TERM: "xterm-256color"
      NODE_ENV: "production"
      POSTGRES_DB: "oni"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: ""
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /postgresql/data
    volumes:
      - postgres_data:/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d oni" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    restart: always
    image: rrkive/oni:2.0.1
    depends_on:
      db:
        condition: service_healthy
      opensearch:
        condition: service_healthy
    hostname: api
    tty: true
    environment:
      TERM: "xterm-256color"
      NODE_ENV: "production"
      LOG_LEVEL: "debug"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "root"
      DB_PASSWORD: ""
      DB_DATABASE: "oni"
      SEARCH_HOST: "opensearch"
    volumes:
      - ./configuration.json:/srv/configuration.json
      - /opt/storage/oni:/opt/storage/oni
    ports:
      - "8080:8080"
    command: [ "npm", "run", "prod" ]

  opensearch:
    restart: always
    image: opensearchproject/opensearch:2.13.0
    hostname: opensearch
    tty: true
    environment:
      - TERM="xterm-256color"
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      #- xpack.security.enabled=false # for elasticsearch
      - plugins.security.disabled=true # for opensearch
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=ASd8asfhqu2i3r@#$1546
    volumes:
      - opensearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
